### ISSUE TITLE
Créer une section "Dernier meetup"

### ISSUE THREAD

**Issue by Nigui** [BlockchainEtSociete/BlockchainEtSociete.github.io#14]
En parlant avec @dlecan, nous pensons qu'il serait bon d'ajouter une section "dernier meetup" qui (comme son nom l'indique) afficherait le dernier meetup qui a eu lieu. 

Graphiquement, les deux blocs ("dernier meetup" et "prochain meetup") pourraient être sur la même ligne (quand il y a de la place).

**Comment by devsheder** [comment]
Yep j'ai vu ça. Je m'étais basé sur ce qui était indiqué en dur.
Je vais voir ça.

**Comment by dlecan** [comment]
Fix by #13 and #19

**Comment by Nigui** [comment]
Pourquoi cette issue est fermée ? 
L'idée était de faire cohabiter "dernier meetup" et "prochain meetup" pour qu'il y ai toujours une section "meetup". 
Peut être mal formulé, désolé.

**Comment by dlecan** [comment]
Mal compris de mon côté :)
