### ISSUE TITLE
Récupérer les infos d'un event depuis API meetup

### ISSUE THREAD

**Issue by Nigui** [BlockchainEtSociete/BlockchainEtSociete.github.io#4]
L'idée est de remplir automatiquement la section "prochain meetup" à partir des informations saisies sur la page meetup. 

Documentation API meetup : https://www.meetup.com/meetup_api/docs/:urlname/events/#list

Les items à récupérer : 
- name
- local_date
- local_time + time
- duration
- venu.name 
- venu.lat
- venu.lon
- venu.address_1
- venu.city

**Comment by devsheder** [comment]
@Nigui 
Mince, je n'avais pas vu cette issue
Dis moi si c'est bon ma PR https://github.com/BlockchainEtSociete/BlockchainEtSociete.github.io/pull/13 sinon je modifie
Merci
